### ISSUE TITLE
A SortedSparseArray class?

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/SparseArray#4]
It may be helpful to impose some kind of order on the non-zero elements in the SparseArray, to make it more efficient to search for particular elements. For example, one could imagine ordering non-zero values by the index of the slowest-changing dimensions. This would enable us, e.g., to efficiently convert 2D blocks into `dgCMatrix` objects during block processing. **beachmat** would also be able to exploit this to provide a more efficient C++ interface to individual rows if it got `SortedSparseArray` inputs.

This would be complementary to chunking considerations, you could also imagine a `SortedChunkedSparseArray` class where each chunk is a `SortedSparseArray` that enables efficient indexing inside the chunk.

**Comment by hpages** [comment]
Hi Aaron,

The new SVT_SparseArray container uses the new SVT (Sparse Vector Tree) layout to represent the multidimensional sparse data. This supersedes the COO layout used by the old SpaseArraySeed container defined in the **DelayedArray** package and by the COO_SparseArray container defined in the **SparseArray** package (note that COO_SparseArray is just a reincarnation of SpaseArraySeed with a better name and in a better place).

The SVT layout is more efficient than the COO layout, both in terms of memory footprint and speed of operations in general. For example:
```
library(SparseArray)
svt <- poissonSparseMatrix(45000, 8000, density=0.08)
object.size(svt) / 1024 / 1024
# 221.1 bytes

system.time(dgc <- as(svt, "dgCMatrix"))
#    user  system elapsed 
#   0.115   0.248   0.363

library(DelayedArray)
sas <- as(dgc, "SparseArraySeed")
type(sas@nzdata) <- "integer"
object.size(sas) / 1024 / 1024
# 329.7 bytes

system.time(dgc2 <- as(sas, "dgCMatrix"))
#    user  system elapsed 
#   0.722   0.416   1.138

identical(dgc2, dgc)
# [1] TRUE
```
This is just one example. Almost every operation supported by these objects is faster with the SVT layout.

AFAIK the only operation where the COO layout has a (huge) advantage over the SVT layout is `aperm()`. Yes, `aperm()` is trivial to implement, and is cheap, on a SpaseArraySeed or COO_SparseArray object, but is a lot more complicated to implement, and a lot more expensive, on an SVT_SparseArray object. OTOH binding operations (e.g. `cbind()` or `acbind()`) are very easy to implement and a lot faster on the latter (tens to hundreds times faster!).

Anyways, after spending many hours implementing and optimizing `aperm()` on  SVT_SparseArray objects 2 weeks ago, I'd say it performs well enough.

For these reasons I'm planning to use SVT_SparseArray objects internally in **DelayedArray** for things like `extract_sparse_array()`, `read_block(..., as.sparse=TRUE)`, and `blockApply(..., as.sparse=TRUE)`, instead of SparseArraySeed objects. See [TODO file](https://github.com/Bioconductor/DelayedArray/blob/devel/TODO) in **DelayedArray** for the details and timeline of this migration.

The long term plan is to get rid of SparseArraySeed objects. I'll keep COO_SparseArray objects around, mainly as a curiosity, but I don't intent to put a lot of effort into implementing new operations for these objects. All my efforts wiill be on supporting and improving SVT_SparseArray objects.

I don't know what the implications of these changes are on your plans with **beachmat** future developments. Let me know how easy/hard it will be for you to adopt SVT_SparseArray and if there are things we should add to **SparseArray** to make this adoption easier.

Thanks,
H.

**Comment by LTLA** [comment]
Interesting. So, in the 2D case, the SVT structure is equivalent to a CSC matrix, but it basically splits up the values and indices into separate vectors for each column. 

I think this should be fairly straightforward to accommodate in the new **tatami** interface, which is where the new C++ development is going. I'd prefer to avoid changing **beachmat**'s original API, as I'm trying to get everyone to move over to **tatami** anyway. As long as the old `SparseArraySeed` sticks around for the short-medium term, we should be fine.

**Comment by hpages** [comment]
> So, in the 2D case, the SVT structure is equivalent to a CSC matrix, but it basically splits up the values and indices into separate vectors for each column.

Exactly! Various benefits to this:
- column extraction is trivial and more efficient (no copy)
- `cbind()` is trivial and a lot more efficient (no copy)
- `rbind()` is also relatively easy and more efficient
- subassignment is a lot more efficient (it's painfully slow with a dgCMatrix object)
- and last but not least: supporting >= 2^31 non-zero values does not require using long vectors which is what dgCMatrix objects would need to do (for their `@i` and `@x` slots) if they wanted to support that. Problem is that all the operations above require copying the `i` and `x` vectors stored in the `@i` and/or `@x` slots. This becomes very expensive as the size of these vectors increases.

> As long as the old SparseArraySeed sticks around for the short-medium term, we should be fine.

It will but I want to get rid of it at some point because it's now reincarnated in **SparseArray** as COO_SparseArray. I don't intend to touch COO_SparseArray so this one will stick around, although I don't intend to do any major improvements to it.

**Comment by LTLA** [comment]
The vendored **tatami** libraries (and the associated `beachmat::initializeCpp()`) have now transitioned to the new `SVT_SparseMatrix`, with additional support for `COO_SparseMatrix` from `extract_sparse_array()`. 

That said, the legacy **beachmat** C++ library is still expecting `SparseArraySeed`s as input. I don't have an easy timeline for that because it's dependent on downstream developers moving along.

**Comment by hpages** [comment]
oops, I just renamed the `@nzvals` slot -> `@nzdata` a few days ago (see 50ec590f912aa29a97d02f39754bff9e31958d18). Bad timing sorry!

Of course `SparseArraySeed` will go thru a full 1-year `.Deprecated`/`.Defunct` cycle so downstream developers will have to move along anyways.

**Comment by hpages** [comment]
> Of course SparseArraySeed will go thru a full 1-year .Deprecated/.Defunct cycle so downstream developers will have to move along anyways.

**An update on this:** SparseArraySeed is still around and not deprecated yet. All code should stick to `OLD_extract_sparse_asrray()` for sparse extraction, which returns a good ol' SparseArraySeed. The new `extract_sparse_asrray()` will return an SVT_SparseArray or COO_SparseArray but is not ready yet.

No plans for a SortedSparseArray class so closing this.
